package com.khizhny.freepasswordkeeper;

import android.content.ContentValues;

import java.util.ArrayList;
import java.util.List;

class Category extends Node {


		List<Entry> entryList = new ArrayList<>();  // Entries stored in category
		List<Category> categoryList = new ArrayList<>(); // subCategories
		User user; // back reference to user

		Category parent=null; // back reference to parent Category

		/**
		 * Constructor for root category
		 * @param user
		 */
		Category(User user){
				this.name="root";
				this.user=user;
				user.rootCategory=this;
		}

		/**
		 * Constructor for subcategories
		 * @param parentCategory
		 * @param name
		 */
		Category(Category parentCategory, String name){
				this.name=name;
				this.user=parentCategory.user;
				this.parent=parentCategory;
				parentCategory.categoryList.add(this);
		}

		public ContentValues getContentValues(){
				ContentValues cv = new ContentValues();
				try {
						if (id>=1) cv.put("_id",id); // will be generated by DB

						cv.put("name", user.decrypter.encrypt(name));
						cv.put("user_id",user.id);

						if (parent==null) {
								cv.put("parent_id",user.id);
						} else{
								cv.put("parent_id",parent.id);
						}

				} catch (Exception e) {
						e.printStackTrace();
				}
				return cv;
		}

}
