package com.khizhny.freepasswordkeeper;

import android.content.ContentValues;

import java.util.ArrayList;
import java.util.List;

class Category extends Node {


		final List<Entry> entryList = new ArrayList<>();  // Entries stored in category
		final List<Category> categoryList = new ArrayList<>(); // subCategories
		final User user; // back reference to user



		/**
		 * Constructor for root category
		 * @param user User
		 */
		Category(User user){
				this.name="root";
				this.user=user;
				user.rootCategory=this;
		}

		/**
		 * Constructor for subcategories
		 * @param parentCategory Parent category
		 * @param name Name
		 */
		Category(Category parentCategory, String name){
				this.name=name;
				this.user=parentCategory.user;
				this.parent=parentCategory;
				parentCategory.categoryList.add(this);
		}

		@Override
		public ContentValues getContentValues(){
				ContentValues cv = new ContentValues();
				try {
						if (id>=1) cv.put("_id",id); // will be generated by DB

						if (user.rootCategory!=this){
							cv.put("name", user.decrypter.encrypt(name));
						}else {
							cv.put("name", name); // root category name not encrypted
						}

						cv.put("user_id",user.id);

						if (parent!=null) {
								cv.put("parent_id",parent.id);
						}

				} catch (Exception e) {
						e.printStackTrace();
				}
				return cv;
		}

}
