package com.khizhny.freepasswordkeeper;

import android.content.ContentValues;

class Entry extends Node {

		// information
		String password;
		String login;
		String url;
		String comment;

		// references
		private User user; //Back ref to user

		Entry(Category category, String password,String login,String name,String comment,String url,int id){
				this.password=password;
				this.login=login;
				this.parent=category;
				this.parent.entryList.add(this);
				this.user=category.user;
				this.name=name;
				this.comment=comment;
				this.url=url;
				this.id=id;
		}

		/**
		 *
		 * @return encrypted values for db
		 */
		@Override
		public ContentValues getContentValues(){
				ContentValues cv = new ContentValues();
				if (id>=1) cv.put("_id",id); // will be generated by DB
				cv.put("category_id",parent.id);
				if (!password.equals("")) {
						cv.put("password",user.decrypter.encrypt(password));
				}else{
						cv.put("password","");
				}
				if (!login.equals("")) {
						cv.put("login",user.decrypter.encrypt(login));
				}else{
						cv.put("login","");
				}
				if (!name.equals("")) {
						cv.put("name",user.decrypter.encrypt(name));
				}else {
						cv.put("name","");
				}
				if (!url.equals("")) {
						cv.put("url",user.decrypter.encrypt(url));
				}else{
						cv.put("url","");
				}
				if (!comment.equals("")){
						cv.put("comment",user.decrypter.encrypt(comment));
				}else {
						cv.put("comment","");
				}
				return cv;
		}
}
