package com.khizhny.freepasswordkeeper;

import android.content.ContentValues;

class Entry extends Node {

		String password="";
		String login="";
		String url="";
		String comment="";
		Category category;

		Entry(Category category, String password,String login,String name){
				this.password=password;
				this.login=login;
				this.category=category;
				this.category.entryList.add(this);
				this.name=name;
		}

		public ContentValues getContentValues(){
				ContentValues cv = new ContentValues();
				if (!password.equals("")) try {
						if (id>=1) cv.put("_id",id); // will be generated by DB
						cv.put("password",category.user.decrypter.encrypt(password));
						if (!login.equals("")) cv.put("login",category.user.decrypter.encrypt(login));
						if (!name.equals("")) cv.put("name",category.user.decrypter.encrypt(login));
						if (!url.equals("")) cv.put("url",category.user.decrypter.encrypt(url));
						if (!comment.equals(""))	cv.put("comment",category.user.decrypter.encrypt(comment));
						cv.put("category_id",category.id);
				} catch (Exception e) {
						e.printStackTrace();
						return null;
				}
				return cv;
		}
}
