package com.khizhny.freepasswordkeeper;

import android.content.ContentValues;

abstract class Node {
		int id=-1;			 	// will be autogenerated in DB after save
		String name;			// Name of Entry, Category or User
		Node parent=null; // back reference to parent Category. null for root categories

		abstract public ContentValues getContentValues();

		@Override
		public String toString() {
				return name;
		}
}
