package com.khizhny.freepasswordkeeper;

import android.content.ContentValues;

class User extends Node {

		String name_encrypted;

		Category rootCategory=new Category(this);

		Decrypter decrypter;

		User(String name, int id){
				this.name=name;
				this.id=id;
		}
		@Override
		public ContentValues getContentValues(){
				ContentValues cv = new ContentValues();
				if (id>=1) cv.put("_id",id); // will be generated by DB
				cv.put("name",name);
				cv.put("name_encrypted",decrypter.encrypt(name));  // used to check password
				return cv;
		}

		public boolean checkPassword(){
				return name_encrypted.equals(decrypter.encrypt(name));
		}
}
